// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ekitap.data.Concrete.EfCore;

namespace ekitap.data.Migrations
{
    [DbContext(typeof(ekitapContext))]
    [Migration("20211103230855_AddTables")]
    partial class AddTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ekitap.entity.Sepet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sepets");
                });

            modelBuilder.Entity("ekitap.entity.SepetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("SepetId")
                        .HasColumnType("int");

                    b.Property<int>("kitapId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SepetId");

                    b.HasIndex("kitapId");

                    b.ToTable("SepetItems");
                });

            modelBuilder.Entity("ekitap.entity.kategori", b =>
                {
                    b.Property<int>("kategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ka_adi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("kategoriId");

                    b.ToTable("kategoriler");
                });

            modelBuilder.Entity("ekitap.entity.kitap", b =>
                {
                    b.Property<int>("kitapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EkZaman")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("k_aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("k_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("k_anasayfa")
                        .HasColumnType("bit");

                    b.Property<double?>("k_fiyat")
                        .HasColumnType("float");

                    b.Property<bool>("k_onay")
                        .HasColumnType("bit");

                    b.Property<string>("k_resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("k_sayfa")
                        .HasColumnType("int");

                    b.Property<int>("kategoriId")
                        .HasColumnType("int");

                    b.Property<int>("yayineviId")
                        .HasColumnType("int");

                    b.HasKey("kitapId");

                    b.HasIndex("kategoriId");

                    b.HasIndex("yayineviId");

                    b.ToTable("kitaplar");
                });

            modelBuilder.Entity("ekitap.entity.kitapyazar", b =>
                {
                    b.Property<int>("yazarId")
                        .HasColumnType("int");

                    b.Property<int>("kitapId")
                        .HasColumnType("int");

                    b.HasKey("yazarId", "kitapId");

                    b.HasIndex("kitapId");

                    b.ToTable("kitapyazar");
                });

            modelBuilder.Entity("ekitap.entity.yayinevi", b =>
                {
                    b.Property<int>("yayineviId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("yayineviAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("yayineviId");

                    b.ToTable("yayinevleri");
                });

            modelBuilder.Entity("ekitap.entity.yazar", b =>
                {
                    b.Property<int>("yazarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("yazarad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yazarsoyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("yazarId");

                    b.ToTable("yazarlar");
                });

            modelBuilder.Entity("ekitap.entity.SepetItem", b =>
                {
                    b.HasOne("ekitap.entity.Sepet", "Sepet")
                        .WithMany("SepetItems")
                        .HasForeignKey("SepetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ekitap.entity.kitap", "kitap")
                        .WithMany()
                        .HasForeignKey("kitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ekitap.entity.kitap", b =>
                {
                    b.HasOne("ekitap.entity.kategori", "kategori")
                        .WithMany("kitaplar")
                        .HasForeignKey("kategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ekitap.entity.yayinevi", "yayinevi")
                        .WithMany("kitaplar")
                        .HasForeignKey("yayineviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ekitap.entity.kitapyazar", b =>
                {
                    b.HasOne("ekitap.entity.kitap", "kitap")
                        .WithMany("kitapyazarlar")
                        .HasForeignKey("kitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ekitap.entity.yazar", "yazar")
                        .WithMany("kitapyazarlar")
                        .HasForeignKey("yazarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
